refactor/missing-python-library-in-requirements
```
Traceback (most recent call last):
  File "scan_log4j_versions.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```